export const matchDayStyles = {
  selectorRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: 14,
    alignItems: "flex-start",
    flexWrap: "wrap",
    marginBottom: 22,
    padding: 16,
    borderRadius: 18,
    background: "rgba(255,255,255,0.035)",
    border: "1px solid rgba(255,255,255,0.08)",
  },
  commandHead: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 16,
    flexWrap: "wrap",
  },
  commandEyebrow: {
    margin: "0 0 6px",
    color: "#38bdf8",
    fontSize: 12,
    fontWeight: 900,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  commandTitle: {
    margin: "0 0 6px",
    fontSize: 24,
    lineHeight: 1.1,
  },
  readinessBox: {
    minWidth: 118,
    borderRadius: 16,
    padding: "12px 14px",
    display: "grid",
    gap: 4,
    textAlign: "right",
    background: "rgba(56,189,248,0.10)",
    border: "1px solid rgba(56,189,248,0.24)",
    color: "#bfdbfe",
  },
  progressTrack: {
    position: "relative",
    height: 8,
    borderRadius: 999,
    overflow: "hidden",
    margin: "16px 0",
    background: "rgba(255,255,255,0.08)",
  },
  progressFill: {
    position: "absolute",
    inset: 0,
    borderRadius: 999,
    background: "linear-gradient(90deg,#38bdf8,#22c55e)",
  },
  commandGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit,minmax(170px,1fr))",
    gap: 10,
  },
  commandCard: {
    border: "1px solid rgba(255,255,255,0.08)",
    borderRadius: 14,
    padding: 12,
    background: "rgba(15,23,42,0.72)",
    color: "#cbd5e1",
    display: "grid",
    gap: 8,
    textAlign: "left",
    cursor: "pointer",
  },
  commandCardDone: {
    border: "1px solid rgba(34,197,94,0.28)",
    background: "rgba(34,197,94,0.08)",
  },
  commandCardTop: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  checkDone: {
    width: 20,
    height: 20,
    borderRadius: 999,
    display: "grid",
    placeItems: "center",
    background: "rgba(34,197,94,0.18)",
    color: "#86efac",
    fontWeight: 900,
  },
  checkTodo: {
    width: 20,
    height: 20,
    borderRadius: 999,
    display: "grid",
    placeItems: "center",
    background: "rgba(245,158,11,0.14)",
    color: "#fcd34d",
    fontWeight: 900,
  },
  commandAction: {
    color: "#38bdf8",
    fontSize: 12,
    fontWeight: 900,
  },
  commandFooter: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
    marginTop: 14,
    paddingTop: 14,
    borderTop: "1px solid rgba(255,255,255,0.07)",
  },
  openAlerts: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    color: "#fcd34d",
    fontSize: 12,
    fontWeight: 800,
  },
  commandLinks: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
  },
  actions: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap",
  },
  printArea: {
    display: "grid",
    gap: 22,
  },
  matchHeader: {
    display: "grid",
    gridTemplateColumns: "160px 1fr 160px",
    alignItems: "center",
    gap: 18,
  },
  matchTitle: {
    margin: "12px 0 6px",
    textAlign: "center",
  },
  scoreBox: {
    textAlign: "center",
  },
  muted: {
    color: "#94a3b8",
    margin: 0,
    lineHeight: 1.5,
  },
  teamMark: {
    display: "grid",
    placeItems: "center",
    gap: 10,
    textAlign: "center",
    minWidth: 0,
  },
  teamLogoFrame: {
    width: 68,
    height: 68,
    borderRadius: 16,
    overflow: "hidden",
    display: "grid",
    placeItems: "center",
    border: "1px solid rgba(255,255,255,0.12)",
  },
  teamLogo: {
    maxWidth: "160%",
    maxHeight: "160%",
    objectFit: "contain",
    transition: "width 0.2s ease, height 0.2s ease",
  },
  teamFallback: {
    width: 68,
    height: 68,
    borderRadius: 16,
    display: "grid",
    placeItems: "center",
    background: "linear-gradient(135deg,#2563eb,#38bdf8)",
    fontWeight: 900,
    fontSize: 24,
  },
  kpiGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit,minmax(130px,1fr))",
    gap: 12,
    marginTop: 22,
  },
  statCard: {
    display: "grid",
    gap: 6,
    padding: 14,
    borderRadius: 12,
    background: "rgba(255,255,255,0.045)",
    border: "1px solid rgba(255,255,255,0.08)",
    color: "#94a3b8",
  },
  mainGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 18,
  },
  checklistMetaGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit,minmax(180px,1fr))",
    gap: 10,
    marginBottom: 14,
  },
  smallField: {
    display: "grid",
    gap: 6,
    color: "#94a3b8",
    fontSize: 11,
    fontWeight: 900,
    textTransform: "uppercase",
    letterSpacing: 0,
  },
  smallInput: {
    width: "100%",
    borderRadius: 10,
    border: "1px solid rgba(255,255,255,0.1)",
    background: "rgba(15,23,42,0.82)",
    color: "white",
    padding: "9px 10px",
    boxSizing: "border-box",
  },
  checklistGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit,minmax(230px,1fr))",
    gap: 10,
  },
  checklistItem: {
    display: "grid",
    gridTemplateColumns: "24px 1fr",
    gap: 10,
    alignItems: "start",
    textAlign: "left",
    border: "1px solid rgba(255,255,255,0.08)",
    borderRadius: 12,
    padding: 12,
    background: "rgba(255,255,255,0.04)",
    color: "#e2e8f0",
    cursor: "pointer",
  },
  checklistItemDone: {
    border: "1px solid rgba(34,197,94,0.32)",
    background: "rgba(34,197,94,0.1)",
  },
  checkIconTodo: {
    width: 22,
    height: 22,
    borderRadius: 8,
    border: "1px solid rgba(148,163,184,0.4)",
    background: "rgba(15,23,42,0.8)",
  },
  checkIconDone: {
    width: 22,
    height: 22,
    borderRadius: 8,
    display: "grid",
    placeItems: "center",
    background: "rgba(34,197,94,0.22)",
    color: "#86efac",
    fontWeight: 900,
  },
  printChecklistSummary: {
    display: "grid",
    gap: 10,
    marginTop: 14,
    padding: 14,
    borderRadius: 12,
    background: "rgba(15,23,42,0.55)",
    border: "1px solid rgba(255,255,255,0.08)",
  },
  printChecklistHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: 10,
    flexWrap: "wrap",
    color: "#e2e8f0",
  },
  printChecklistInfo: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap",
    color: "#94a3b8",
    fontSize: 12,
    fontWeight: 700,
  },
  printChecklistRows: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit,minmax(220px,1fr))",
    gap: 8,
  },
  printChecklistRow: {
    display: "grid",
    gridTemplateColumns: "64px 1fr",
    gap: 6,
    alignItems: "start",
    padding: 10,
    borderRadius: 10,
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(255,255,255,0.07)",
  },
  printStatusDone: {
    color: "#86efac",
    fontSize: 11,
    fontWeight: 900,
    textTransform: "uppercase",
  },
  printStatusTodo: {
    color: "#fbbf24",
    fontSize: 11,
    fontWeight: 900,
    textTransform: "uppercase",
  },
  printChecklistNotes: {
    margin: 0,
    color: "#cbd5e1",
    whiteSpace: "pre-wrap",
    lineHeight: 1.5,
  },
  sectionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    marginBottom: 16,
  },
  playerList: {
    display: "grid",
    gap: 10,
  },
  playerRow: {
    display: "grid",
    gridTemplateColumns: "46px 1fr minmax(120px, 0.7fr) auto auto auto",
    gap: 12,
    alignItems: "center",
    padding: 12,
    borderRadius: 12,
    background: "rgba(255,255,255,0.045)",
    border: "1px solid rgba(255,255,255,0.08)",
  },
  playerAvatar: {
    width: 46,
    height: 46,
    borderRadius: 12,
    display: "grid",
    placeItems: "center",
    overflow: "hidden",
    background: "rgba(56,189,248,0.16)",
    fontWeight: 900,
  },
  avatarImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  playerInfo: {
    display: "grid",
    gap: 4,
    minWidth: 0,
  },
  roleInput: {
    width: "100%",
    borderRadius: 10,
    border: "1px solid rgba(255,255,255,0.1)",
    background: "rgba(15,23,42,0.82)",
    color: "white",
    padding: "9px 10px",
  },
  moveButtons: {
    display: "flex",
    gap: 4,
  },
  scoutingGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit,minmax(220px,1fr))",
    gap: 12,
    marginBottom: 18,
  },
  opponentHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "center",
    marginBottom: 12,
    flexWrap: "wrap",
  },
  opponentList: {
    display: "grid",
    gap: 10,
  },
  opponentRow: {
    display: "grid",
    gridTemplateColumns: "70px 1fr 90px 130px 130px 1fr auto",
    gap: 8,
    alignItems: "center",
  },
  compactInput: {
    width: "100%",
    borderRadius: 10,
    border: "1px solid rgba(255,255,255,0.1)",
    background: "rgba(15,23,42,0.82)",
    color: "white",
    padding: "9px 10px",
  },
  attachmentBox: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    flexWrap: "wrap",
    marginTop: 14,
    padding: 14,
    borderRadius: 14,
    background: "rgba(59,130,246,0.07)",
    border: "1px solid rgba(59,130,246,0.18)",
  },
  attachmentActions: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
  },
  attachmentLink: {
    color: "#93c5fd",
    fontSize: 13,
    fontWeight: 800,
    textDecoration: "none",
    wordBreak: "break-word",
  },
  uploadButton: {
    borderRadius: 10,
    border: "1px solid rgba(59,130,246,0.35)",
    background: "rgba(59,130,246,0.14)",
    color: "#bfdbfe",
    cursor: "pointer",
    padding: "9px 13px",
    fontSize: 13,
    fontWeight: 800,
  },
  previousBox: {
    display: "grid",
    gap: 10,
    marginTop: 18,
    padding: 14,
    borderRadius: 12,
    background: "rgba(56,189,248,0.08)",
    border: "1px solid rgba(56,189,248,0.18)",
  },
  previousItem: {
    display: "grid",
    gap: 4,
    color: "#cbd5e1",
  },

  // Piano di gara labels
  planLabel: {
    margin: "0 0 6px",
    fontSize: 13,
    fontWeight: 800,
    color: "#94a3b8",
    lineHeight: 1.2,
  },

  // Risultato inline nel header
  resultRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 12,
  },
  resultLabel: {
    fontSize: 11,
    fontWeight: 900,
    textTransform: "uppercase",
    color: "#64748b",
    letterSpacing: 0.4,
  },
  resultInput: {
    width: 88,
    padding: "5px 10px",
    borderRadius: 10,
    border: "1px solid rgba(255,255,255,0.15)",
    background: "rgba(255,255,255,0.07)",
    color: "white",
    fontSize: 16,
    fontWeight: 900,
    textAlign: "center",
    outline: "none",
  },

  // Import dalla convocazione
  importBanner: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 14,
    flexWrap: "wrap",
    padding: "14px 18px",
    borderRadius: 14,
    background: "rgba(59,130,246,0.1)",
    border: "1px solid rgba(59,130,246,0.3)",
  },
  prefillBanner: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 14,
    flexWrap: "wrap",
    padding: "14px 18px",
    borderRadius: 14,
    background: "rgba(14,165,233,0.08)",
    border: "1px solid rgba(14,165,233,0.24)",
  },
  prefillMeta: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    marginTop: 8,
    color: "#94a3b8",
    fontSize: 12,
    fontWeight: 700,
  },

  // Banner convocazione
  convoBanner: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    flexWrap: "wrap",
    padding: "12px 16px",
    borderRadius: 14,
    background: "rgba(245,158,11,0.1)",
    border: "1px solid rgba(245,158,11,0.28)",
    marginBottom: 4,
  },
  convoBannerText: {
    fontSize: 13,
    fontWeight: 700,
    color: "#fcd34d",
    lineHeight: 1.4,
  },
};
